In [1]:
import numpy as np

In [2]:
# 初始化模型参数
A = np.array([[0.5, 0.2, 0.3],
                   [0.3, 0.5, 0.2],
                   [0.2, 0.3, 0.5]])
B = np.array([[0.5, 0.5],
                   [0.4, 0.6],
                   [0.7, 0.3]])
PI = np.array([0.2, 0.4, 0.4])
O = [0, 1, 0]
print('A=\n', A)
print('B=\n', B)
print('PI=\n', PI)
print('O=\n', O)

A=
 [[0.5 0.2 0.3]
 [0.3 0.5 0.2]
 [0.2 0.3 0.5]]
B=
 [[0.5 0.5]
 [0.4 0.6]
 [0.7 0.3]]
PI=
 [0.2 0.4 0.4]
O=
 [0, 1, 0]


In [3]:
# viterbi算法中初始化delta_1
delta_1 = PI * B[:, 0]
# viterbi算法中初始化kesi_1
kesi_1 = np.zeros(PI.size, dtype=np.int)
print('delta_1=', delta_1)
print('kesi_1=', kesi_1)
# 最优路径记录初始化
kesi = np.array(kesi_1.T)
print('best_path=', kesi, kesi.shape)

delta_1= [0.1  0.16 0.28]
kesi_1= [0 0 0]
best_path= [0 0 0] (3,)


In [4]:
# 递推
delta_tplusone = delta_1.copy()
for t in range(1, len(O)):
    max_delta_tminus_aji = np.tile(delta_tplusone, PI.size).reshape(A.shape).T*A
    delta_t = np.max(max_delta_tminus_aji, 0)*B[:,O[t]]
    kesi_t = np.argmax(max_delta_tminus_aji, 0)
    kesi = np.column_stack((kesi, kesi_t.T))
    print('delta_%d= ' % (t+1), delta_t)
    print('kesi_%d = ' % (t+1), kesi_t)
    delta_tplusone = delta_t.copy()
print('kesi=\n', kesi)

delta_2=  [0.028  0.0504 0.042 ]
kesi_2 =  [2 2 2]
delta_3=  [0.00756 0.01008 0.0147 ]
kesi_3 =  [1 1 2]
kesi=
 [[0 2 1]
 [0 2 1]
 [0 2 2]]


In [5]:
# 终止
P_star = np.max(delta_t)
i_T_star = np.argmax(kesi_t)
print('P_star=', P_star)
print('i_T_star=', i_T_star)

P_star= 0.014699999999999998
i_T_star= 2


In [6]:
# 最优路径回溯
print('kesi', kesi)
I_star = [i_T_star]
i_tplus_star = i_T_star
for t in range(kesi.shape[1]-1, 0, -1):
    i_t_star = kesi[:,t][i_tplus_star]
    I_star.append(i_t_star)
    i_tplus_star = i_t_star
I_star = I_star[::-1]
print(I_star)

kesi [[0 2 1]
 [0 2 1]
 [0 2 2]]
[2, 2, 2]
